services:
    nginx:
        container_name: forum-nginx
        image: nginx:alpine
        ports:
            - 80:80
            - 443:443
        volumes:
            - .:/app
            - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./etc/nginx/fastcgi_params:/etc/nginx/fastcgi_params
            - ./etc/nginx/dev.crt:/etc/nginx/nginx.crt
            - ./etc/nginx/dev.key:/etc/nginx/nginx.key
        links:
            - php

    php:
        container_name: forum-php
        image: sunfoxcz/php:8.3-fpm
        environment:
            - NETTE_DEVEL=1
        volumes:
            - .:/app
            - ./etc/php/pool.conf:/etc/php/8.3/fpm/pool.d/www.conf
        links:
            - mysql

    mysql:
        container_name: forum-db
        image: percona:8.0
        environment:
            - MYSQL_ROOT_PASSWORD=forum
            - MYSQL_DATABASE=forum
            - MYSQL_USER=forum
            - MYSQL_PASSWORD=forum
        volumes:
            - mysql-data:/var/lib/mysql
            - ./etc/mysql:/docker-entrypoint-initdb.d
            - ./etc/mysql/mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf

    adminer:
        container_name: forum-adminer
        image: adminer:fastcgi
        links:
            - "mysql:db"

volumes:
    mysql-data:
