version: '3'
services:
    nginx:
        container_name: forum-nginx
        image: nginx:alpine
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./etc/nginx/fastcgi_params:/etc/nginx/fastcgi_params
            - ./etc/nginx/dev.crt:/etc/nginx/nginx.crt
            - ./etc/nginx/dev.key:/etc/nginx/nginx.key
            - .:/srv
        links:
            - php

    php:
        container_name: forum-php
        image: sunfoxcz/php:7.3-fpm
        environment:
            - NETTE_DEVEL=1
        volumes:
            - ./etc/php/pool.conf:/etc/php/7.3/fpm/pool.d/www.conf
            - .:/srv
        links:
            - mysql

    mysql:
        container_name: forum-db
        image: mysql:5.7
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_ROOT_PASSWORD=
        volumes:
            - mysql-data:/var/lib/mysql
            - ./etc/mysql:/docker-entrypoint-initdb.d
            - ./etc/mysql/mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf

    adminer:
        container_name: forum-adminer
        image: adminer:fastcgi
        links:
            - "mysql:db"

volumes:
    mysql-data:
